#!/usr/bin/env bash
# This script displays the PID and full process name of processes containing the word "bash."

# Use ps to find and display PIDs and full process names of processes containing "bash"
ps -e | grep bash | awk '{print "For PID: "$1", Full Process Name: "$4}'
