#!/usr/bin/env bash
# Displays a string indefinitely with a sleep period of 2

while true
do 
    echo "To infinity and beyond"
    sleep 2
    trap 'kill -TERM $(pgrep -f "7-highlander")' SIGTERM
done
